// core
import { Component } from '@angular/core';

// service
import { DataService } from './service/data.service';
import { JsPlumbService } from './service/jsPlumb.service';

// class
import { Data }  from './class/data';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  data:Data;

  constructor( private dataService: DataService, private jsPlumbService: JsPlumbService ) {
    console.log('AppComponent.constructor() is called!');
    // @ts-ignore
    this.data = this.dataService.data;
  }

  ngAfterViewInit(){
    console.log('AppComponent.ngAfterViewInit() is called!');
    this.jsPlumbService.init();
  }

  ngAfterViewChecked(){
    //console.log('AppComponent.ngAfterViewChecked() is called!');
    // if(this.dataService.flg_repaint){
    //   this.dataService.flg_repaint = false;
    //   this.jsPlumbService.repaintEverything();
    // }
    this.jsPlumbService.deleteAll();
    this.dataService.loadData({
      "app_type": "web",
      "use_laravel_auth": false,
      "models": [
        {
          "schemas": [
            {
              "id": 1,
              "name": "LDBID",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 1
            },
            {
              "id": 2,
              "name": "AR_ID_ITEM",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 1
            },
            {
              "id": 3,
              "name": "APALT_VALUE",
              "display_name": "",
              "comment": "",
              "type": "float",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 1
            },
            {
              "id": 4,
              "name": "RT_APD_AR_MSTR_DP_RD_id",
              "display_name": "RT_APD_AR_MSTR_DP_RD - NAME",
              "comment": "",
              "type": "integer",
              "input_type": "select",
              "custom_options": "",
              "varidate": "",
              "faker_type": "numberBetween(1,30)",
              "nullable": true,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "RT_APD_AR_MSTR_DP_RD",
              "parent_id": 1
            }
          ],
          "id": 1,
          "name": "RT_AR_BRDNG_DP_RDCS",
          "display_name": "",
          "comment": "",
          "use_soft_delete": false,
          "is_pivot": false,
          "schema_id_for_relation": 1,
          "module": null,
          "pos_x": 328,
          "pos_y": -3,
          "_next_schema_id": 5
        },
        {
          "schemas": [
            {
              "id": 1,
              "name": "LDBID",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 2
            },
            {
              "id": 2,
              "name": "IP_ID_ITEM",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 2
            },
            {
              "id": 3,
              "name": "ARIR_EFCTV_DATE",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 2
            },
            {
              "id": 4,
              "name": "RT_APD_AR_MSTR_DP_RD_id",
              "display_name": "RT_APD_AR_MSTR_DP_RD - NAME",
              "comment": "",
              "type": "integer",
              "input_type": "select",
              "custom_options": "",
              "varidate": "",
              "faker_type": "numberBetween(1,30)",
              "nullable": true,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "RT_APD_AR_MSTR_DP_RD",
              "parent_id": 2
            }
          ],
          "id": 2,
          "name": "TB_AR_IP_RLTNP_DP_RD",
          "display_name": "",
          "comment": "",
          "use_soft_delete": false,
          "is_pivot": false,
          "schema_id_for_relation": 1,
          "module": null,
          "pos_x": 40,
          "pos_y": -6,
          "_next_schema_id": 5
        },
        {
          "schemas": [
            {
              "id": 1,
              "name": "LDBID",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 3
            },
            {
              "id": 2,
              "name": "AR_ID_ITEM",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 3
            },
            {
              "id": 3,
              "name": "REASON_CODE_CLOSE",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 3
            },
            {
              "id": 4,
              "name": "APADP_CLOSE_DATE",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 3
            },
            {
              "id": 5,
              "name": "RT_APD_AR_MSTR_DP_RD_id",
              "display_name": "RT_APD_AR_MSTR_DP_RD - NAME",
              "comment": "",
              "type": "integer",
              "input_type": "select",
              "custom_options": "",
              "varidate": "",
              "faker_type": "numberBetween(1,30)",
              "nullable": true,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "RT_APD_AR_MSTR_DP_RD",
              "parent_id": 3
            }
          ],
          "id": 3,
          "name": "RT_AR_CLOS_DP_RDCS",
          "display_name": "",
          "comment": "",
          "use_soft_delete": false,
          "is_pivot": false,
          "schema_id_for_relation": 1,
          "module": null,
          "pos_x": 35,
          "pos_y": 327,
          "_next_schema_id": 6
        },
        {
          "schemas": [
            {
              "id": 1,
              "name": "LDBID",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 4
            },
            {
              "id": 2,
              "name": "AR_ID_ITEM",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 4
            },
            {
              "id": 3,
              "name": "APALT_VALUE",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 4
            },
            {
              "id": 4,
              "name": "IP_ID_ITEM",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 4
            },
            {
              "id": 5,
              "name": "ARIR_EFCTV_DATE",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 4
            },
            {
              "id": 6,
              "name": "REASON_CODE_CLOSE",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 4
            },
            {
              "id": 7,
              "name": "APADP_CLOSE_DATE",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 4
            },
            {
              "id": 8,
              "name": "OU_NME",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 4
            },
            {
              "id": 10,
              "name": "RT_AR_DLY_BAL_DP_RD_id",
              "display_name": "RT_AR_DLY_BAL_DP_RD - NAME",
              "comment": "",
              "type": "integer",
              "input_type": "select",
              "custom_options": "",
              "varidate": "",
              "faker_type": "numberBetween(1,30)",
              "nullable": true,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "RT_AR_DLY_BAL_DP_RD",
              "parent_id": 4
            }
          ],
          "id": 4,
          "name": "RT_APD_AR_MSTR_DP_RD",
          "display_name": "",
          "comment": "",
          "use_soft_delete": false,
          "is_pivot": false,
          "schema_id_for_relation": 1,
          "module": null,
          "pos_x": 736,
          "pos_y": 22,
          "_next_schema_id": 11
        },
        {
          "schemas": [
            {
              "id": 1,
              "name": "LDBID",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 5
            },
            {
              "id": 2,
              "name": "OU_ID",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 5
            },
            {
              "id": 3,
              "name": "OU_NME",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 5
            },
            {
              "id": 4,
              "name": "RT_APD_AR_MSTR_DP_RD_id",
              "display_name": "RT_APD_AR_MSTR_DP_RD - NAME",
              "comment": "",
              "type": "integer",
              "input_type": "select",
              "custom_options": "",
              "varidate": "",
              "faker_type": "numberBetween(1,30)",
              "nullable": true,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "RT_APD_AR_MSTR_DP_RD",
              "parent_id": 5
            }
          ],
          "id": 5,
          "name": "TB_ORG_UNIT_MSTR_EO",
          "display_name": "",
          "comment": "",
          "use_soft_delete": false,
          "is_pivot": false,
          "schema_id_for_relation": 1,
          "module": null,
          "pos_x": 352,
          "pos_y": 370,
          "_next_schema_id": 5
        },
        {
          "schemas": [
            {
              "id": 1,
              "name": "LDBID",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 6
            },
            {
              "id": 2,
              "name": "AR_ID_ITEM",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 6
            },
            {
              "id": 3,
              "name": "PSTG_IDFR",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 6
            },
            {
              "id": 4,
              "name": "TRANS_IDFR",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 6
            },
            {
              "id": 5,
              "name": "RT_APD_AR_MSTR_DP_RD_id",
              "display_name": "RT_APD_AR_MSTR_DP_RD - NAME",
              "comment": "",
              "type": "integer",
              "input_type": "select",
              "custom_options": "",
              "varidate": "",
              "faker_type": "numberBetween(1,30)",
              "nullable": true,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "RT_APD_AR_MSTR_DP_RD",
              "parent_id": 6
            }
          ],
          "id": 6,
          "name": "RT_TRANS_HIST_DP_RD",
          "display_name": "",
          "comment": "",
          "use_soft_delete": false,
          "is_pivot": false,
          "schema_id_for_relation": 1,
          "module": null,
          "pos_x": 1179,
          "pos_y": -1,
          "_next_schema_id": 6
        },
        {
          "schemas": [
            {
              "id": 1,
              "name": "LDBID",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 7
            },
            {
              "id": 2,
              "name": "AR_ID_ITEM",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 7
            },
            {
              "id": 3,
              "name": "LDGR_BAL",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 7
            },
            {
              "id": 4,
              "name": "AVAIL_BAL",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 7
            },
            {
              "id": 5,
              "name": "RUNNG_BAL",
              "display_name": "",
              "comment": "",
              "type": "string",
              "input_type": "text",
              "custom_options": "",
              "varidate": "",
              "faker_type": "",
              "nullable": false,
              "unique": false,
              "show_in_list": true,
              "show_in_detail": true,
              "belongsto": "",
              "parent_id": 7
            }
          ],
          "id": 7,
          "name": "RT_AR_DLY_BAL_DP_RD",
          "display_name": "",
          "comment": "",
          "use_soft_delete": false,
          "is_pivot": false,
          "schema_id_for_relation": 1,
          "module": null,
          "pos_x": 1170,
          "pos_y": 334,
          "_next_schema_id": 6
        }
      ],
      "tool": "ER-DIAGRAM-TOOL",
      "_next_model_id": 8
    });
  }
}
